name: 'nation_scorecard'
version: '1.0.0'
config-version: 2

profile: 'nation_scorecard'

model-paths: ["models"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nation_scorecard:
    marts:
      +materialized: table
