name: tpch_revenue_by_region
version: "1.0.0"
config-version: 2

profile: tpch_revenue_by_region

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tpch_revenue_by_region:
    marts:
      +materialized: table
